services:
  restaurant-service:
    container_name: restaurant-service
    build:
      context: ./restaurant-service
    ports:
      - "4001:4001"
    environment:
      SERVER_PORT: 4001
      SPRING_DATASOURCE_URL: jdbc:postgresql://restaurant_db:5432/${POSTGRES_RESTAURANT_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: true
      SPRING_SQL_INIT_MODE: always
    networks:
      - food-network

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
    ports:
      - "8000:8000"
    environment:
      SERVER_PORT: 8000
    depends_on:
      - restaurant-service
    networks:
      - food-network

  order-service:
    container_name: order-service
    build:
      context: ./order-service
    ports:
      - "4002:4002"
    environment:
      SERVER_PORT: 4002
      SPRING_DATASOURCE_URL: jdbc:postgresql://order_db:5432/${POSTGRES_ORDER_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_HTTP_CLIENT_SERVICE_GROUP_RESTAURANT_BASE_URL: http://restaurant-service:4001
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: true
      SPRING_SQL_INIT_MODE: always
    depends_on:
      - restaurant-service
    networks:
      - food-network


networks:
  food-network:
    external: true