package com.food_delivery.order_service.model;

public enum OrderStatus {
    CREATED, PAYMENT_PENDING, PAYMENT_CONFIRMED, ACCEPTED_BY_RESTAURANT, REJECTED_BY_RESTAURANT,
    PREPARING, READY_FOR_DELIVERY, OUT_FOR_DELIVERY, DELIVERED, CANCELED
}
